//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEdmxModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataAccessPermission
    {
        public int AccessPermissionID { get; set; }
        public string AccessType { get; set; }
    }
}
