//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEdmxModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantUser
    {
        public int PkID { get; set; }
        public Nullable<int> TenantID { get; set; }
        public string AspUserID { get; set; }
        public string AspRoleID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string TenantUserName_ { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
