//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEdmxModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_api_tenants_chat_users
    {
        public int PkID { get; set; }
        public Nullable<int> TenantID { get; set; }
        public string AspUserID { get; set; }
        public string UserName { get; set; }
        public string TenantUserName_ { get; set; }
        public string FullName { get; set; }
    }
}
