//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEdmxModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_api_tenants_my_roles
    {
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> TenantID { get; set; }
    }
}
